name: Release Drafter

on:
  push:
    branches:
      - v7

jobs:
  draftRelease:
    runs-on: ubuntu-latest

    name: Draft Release
    steps:
      - uses: actions/checkout@master
      - name: Draft Release
        uses: toolmantim/release-drafter:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
